_BASE_: "./Base-RCNN-FPN-OPENDET.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
DATASETS:
  TRAIN: ('voc_2007_train', 'voc_2012_trainval')
  TEST: ('voc_2007_test', 'voc_coco_20_40_test', 'voc_coco_20_60_test', 'voc_coco_20_80_test', 'voc_coco_2500_test', 'voc_coco_5000_test', 'voc_coco_10000_test', 'voc_coco_20000_test')
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.010
  STEPS: (42000, 58000)
  MAX_ITER: 64000
  WARMUP_ITERS: 100
  AMP:
    ENABLED: True
UPLOSS:
  WEIGHT: 1.0  # paper is 0.5